[package]
name = "hf-tokenizers"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokenizers = { version = "0.13.4", default-features = false, features = ["onig", "http"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
