name: Publish base docker image
on:
  workflow_dispatch:
env:
  # Tells where to store caches.
  CI_CACHE_DIR: ${{ github.workspace }}/../../ci_cache

jobs:
  publish_base:
    runs-on: [self-hosted, linux, release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build base for cuda 12.1
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile.base
          push: true
          cache-from: type=local,src=$CI_CACHE_DIR/.buildx-cache
          cache-to: type=local,dest=$CI_CACHE_DIR/.buildx-cache
          build-args: |
            UBUNTU_VERSION=22.04
            CUDA_VERSION=12.1
            GCC_VERSION=11
            CMAKE_VERSION=3.18.5
            NINJA_VERSION=1.9.0
          tags: |
            vectorchai/scalellm_builder:cuda12.1-ubuntu22.04
            vectorchai/scalellm_builder:cuda12.1

      - name: Build base for cuda 11.8
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile.base
          push: true
          cache-from: type=local,src=$CI_CACHE_DIR/.buildx-cache
          cache-to: type=local,dest=$CI_CACHE_DIR/.buildx-cache
          build-args: |
            UBUNTU_VERSION=22.04
            CUDA_VERSION=11.8
            GCC_VERSION=11
            CMAKE_VERSION=3.18.5
            NINJA_VERSION=1.9.0
          tags: |
            vectorchai/scalellm_builder:cuda11.8-ubuntu22.04
            vectorchai/scalellm_builder:cuda11.8

